accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountDeleteView, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = "accountapp"


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 
from articleapp.views import *
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='articleapp/list.html'), name ='lists'),
    path('accounts/', include('accountapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('questions/', include('questionapp.urls')),
    path('AIpredictions/', include('AIpredictionapp.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path 
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms 
from django.contrib.auth.models import User

class AccountUpdateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].disabled = True

accountapp/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
import requests
from django.urls import reverse 
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse, reverse_lazy
from accountapp.forms import AccountUpdateForm
from accountapp.decorators import account_ownership_required
import json
from django.template import loader
from django.http import HttpResponse, JsonResponse


has_ownership = [account_ownership_required, login_required]


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html'
    
    
class AccountDetailView(DetailView):
    model = User 
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/update.html'
    
    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User 
    success_url  = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'
    

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>
            회원가입
        </h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post" class="post-form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>
            회원 탈퇴
        </h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        
        
        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt="" style = "height: 12rem; width 12rem; border-radius: 20rem; margin-bottom: 2rem; text-align:center">
        <h2 style="font-family: 'NanumSquareB'; text-align:center">
            {{ target_user.profile.nickname }}
                {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
                   href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    edit 
                </a>
                {% endif %}
        </h2>
        {% else %}
            {% if target_user == user %}
            <a href="{% url 'profileapp:create' %}">
                <h2 style="font-family: 'NanumSquareB'">
                프로필 만들기
                </h2>
            </a>
            {% else %}
            <h2>
                프로필 미설정 
            </h2>
            {% endif %}
        {% endif %}
            
        {% if target_user == user %}
        <a class="material-icons" 
           style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
           href="{% url 'accountapp:update' pk=user.pk %}">
            settings
        </a>
        <a class="material-icons" 
           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
           href="{% url 'accountapp:delete' pk=user.pk %}">
            cancel
        </a>
        {% endif %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h4>
            Login
        </h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include "form_errors.html" %}
            {% bootstrap_form form %}
            <input type="submit" class ="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
    <div class="my-4">
        <p>
            <a role = "button" class="btn btn-outline-secondary" href="{% provider_login_url 'google' %}"><i class="fa-brands fa-google"></i>&nbsp;&nbsp;Google 계정으로 로그인 하기&nbsp;&nbsp;</a>
        </p>
        <p>
            <a href="{% provider_login_url 'kakao' method='oauth2' %}" type="button" class="btn btn-outline-warning">&nbsp;&nbsp;&nbsp;카카오톡 계정으로 로그인 하기&nbsp;&nbsp;&nbsp;</a>
        </p>
        <p>
            <button type="button" class="btn btn-outline-success">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Naver 계정으로 로그인 하기&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
        </p>
    </div>
    <div style="text-align: center; max-width: 500px; margin: 1rem auto">
        <nav>
            <a href="{% url 'accountapp:create' %}">회원가입</a>
        </nav>
    </div>
</div>

    
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>
            수정하기
        </h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}