AIpredictionapp/urls.py
from django.urls import path 
from django.views.generic import TemplateView
import AIpredictionapp.views


app_name = "AIpredictionapp"

urlpatterns = [
    path('AIservice/', AIpredictionapp.views.AIservice, name='AIservice'),
    path('Dataresults/', AIpredictionapp.views.AIservice, name='Dataresults'),
    path('predictionlists/', AIpredictionapp.views.predictionlist, name='predictionlist'),

] 

accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountDeleteView, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = "accountapp"


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path 
from django.views.generic import TemplateView
import articleapp.views 

app_name = 'articleapp'

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('basketproduct/', articleapp.views.basketproduct, name='basketproduct'),
    path('AIproduct/', articleapp.views.AIproduct, name='AIproduct'),
    path('pricing/', articleapp.views.pricing, name='pricing'),
    path('inquiry/', articleapp.views.inquiry, name='inquiry'),
    path('otherinfo/', articleapp.views.otherinfo, name='otherinfo'),
    path('terms/', articleapp.views.terms, name='terms'),
    path('companyinfo/', articleapp.views.companyinfo, name='companyinfo'),
    path('teaminfo/', articleapp.views.teaminfo, name='teaminfo'),
    path('checkout/', articleapp.views.check, name='checkout'),
] 

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 
from articleapp.views import *
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='articleapp/list.html'), name ='lists'),
    path('accounts/', include('accountapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('questions/', include('questionapp.urls')),
    path('AIpredictions/', include('AIpredictionapp.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questionapp/urls.py
from questionapp.views import index
from django.urls import path
from . import views


app_name = 'questionapp'

urlpatterns = [
    path('', index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    path('vote/question/<int:question_id>/', views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', views.vote_answer, name='vote_answer'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    
{% include 'head.html' %}
    
<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}
    
    
    {% block content %}
    {% endblock %}
    
    <hr>
    
    {% include 'footer.html' %}

{% block script %}
{% endblock %}    
    
</body>
</html>

templates/check.html
{% extends 'base.html' %}

{% block content %}

<html lang="en">
  <body class="bg-light">
    
<div class="container">
  <main>
    <div class="py-5 text-center">
      <img class="d-block mx-auto mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
      <h2>Checkout form</h2>
      <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">3</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Product name</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$12</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Second product</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$8</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Third item</h6>
              <small class="text-muted">Brief description</small>
            </div>
            <span class="text-muted">$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>EXAMPLECODE</small>
            </div>
            <span class="text-success">−$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$20</strong>
          </li>
        </ul>

        <form class="card p-2">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </form>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Billing address</h4>
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-6">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" class="form-control" id="username" placeholder="Username" required>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="col-12">
              <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="col-md-5">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" id="country" required>
                <option value="">Choose...</option>
                <option>United States</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>

            <div class="col-md-4">
              <label for="state" class="form-label">State</label>
              <select class="form-select" id="state" required>
                <option value="">Choose...</option>
                <option>California</option>
              </select>
              <div class="invalid-feedback">
                Please provide a valid state.
              </div>
            </div>

            <div class="col-md-3">
              <label for="zip" class="form-label">Zip</label>
              <input type="text" class="form-control" id="zip" placeholder="" required>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>

          <hr class="my-4">

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="same-address">
            <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
          </div>

          <div class="form-check">
            <input type="checkbox" class="form-check-input" id="save-info">
            <label class="form-check-label" for="save-info">Save this information for next time</label>
          </div>

          <hr class="my-4">

          <h4 class="mb-3">Payment</h4>

          <div class="my-3">
            <div class="form-check">
              <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
              <label class="form-check-label" for="credit">Credit card</label>
            </div>
            <div class="form-check">
              <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="debit">Debit card</label>
            </div>
            <div class="form-check">
              <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
              <label class="form-check-label" for="paypal">PayPal</label>
            </div>
          </div>

          <div class="row gy-3">
            <div class="col-md-6">
              <label for="cc-name" class="form-label">Name on card</label>
              <input type="text" class="form-control" id="cc-name" placeholder="" required>
              <small class="text-muted">Full name as displayed on card</small>
              <div class="invalid-feedback">
                Name on card is required
              </div>
            </div>

            <div class="col-md-6">
              <label for="cc-number" class="form-label">Credit card number</label>
              <input type="text" class="form-control" id="cc-number" placeholder="" required>
              <div class="invalid-feedback">
                Credit card number is required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-expiration" class="form-label">Expiration</label>
              <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
              <div class="invalid-feedback">
                Expiration date required
              </div>
            </div>

            <div class="col-md-3">
              <label for="cc-cvv" class="form-label">CVV</label>
              <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
              <div class="invalid-feedback">
                Security code required
              </div>
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
        </form>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017–2022 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="form-validation.js"></script>
  </body>
</html>





{% endblock %}

templates/footer.html
<div class = "pragmatic_footer">
    <div class = "pragmatic_footer_button">
        <a href="{% url 'articleapp:companyinfo' %}" class="pragmatic_header_nav">회사소개</a>
        <a href="{% url 'articleapp:terms' %}" class="pragmatic_header_nav">서비스 이용약관</a>
        <a href="{% url 'articleapp:otherinfo' %}" class="pragmatic_header_nav">공지사항</a>
        <a href="{% url 'articleapp:teaminfo' %}" class="pragmatic_header_nav">팀소개</a>
    </div>
    <div class="my-3">
        <h6 class="pragmatic_logo">
            <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
                Lineless
            </a>
        </h6>
    </div>
</div>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lineless</title>
    
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/carousel/">
    
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/album/">
    
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/checkout/">
    
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/pricing/">
    
    <link rel="canonical" href="https://getbootstrap.com/docs/4.6/examples/product/">
    
    <!-- Swiper Link -->
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    
    <!--  BOOTSTRAP LINK    -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    
    <!-- <link href="https://cdn.js.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3delivr" crossorigin="anonymous"> -->
    <!--  구글 폰트    -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Slab&display=swap" rel="stylesheet">
    
    <!-- 구글 폰트 -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    
    <!-- DEFAULT CSS LINK     -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    
    <!-- main.js -->
    <script src="{% static 'main.js' %}"></script>
    
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/6025519c5c.js" crossorigin="anonymous"></script>
    
    <!-- Chart JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    
    <!-- 카카오 소셜 로그인 -->
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <script>
        
        Kakao.init('c6dafa8a62f01b7192f2bbf6bc98a2e0');
        
        console.log(Kakao.isInitialized());

    </script>
    
    
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    
    <style>
        @font-face {
            font-family: "NanumSquareR";
            src: local('NanumSquareR'),
                url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: "NanumSquareEB";
            src: local('NanumSquareEB'),
                url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: "NanumSquareB";
            src: local('NanumSquareB'),
                url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: "NanumSquareL";
            src: local('NanumSquareL'),
                url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style> 
    

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
    
</head>

templates/header.html
<div class = "pragmatic_header">
    {% include "navbar.html" %}
</div>

templates/navbar.html
{% load static %}
{% load sass_tags %}
<nav class="navbar navbar-expand-lg navbar-light container">
  <a class="navbar-brand" href="{% url 'articleapp:list' %}">
    <img src="{% static '/Logo/lineless_logo_removebg.png' %}" width="200px" height="auto" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  {% if not user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          제품
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'articleapp:basketproduct' %}">스마트바구니</a>
          <a class="dropdown-item" href="{% url 'articleapp:AIproduct' %}">AI수요예측 서비스</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articleapp:pricing' %}">가격</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articleapp:inquiry' %}">제품문의</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questionapp:index' %}">Q&A</a>
      </li>
    </ul>
  </div>
  {% if not user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:login' %}?next={{ request.path }}">Login</a>
      </li>
    </ul>
  </div>
  {% else %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          계정관리
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'accountapp:detail' pk=user.pk %}">내 프로필</a>
          <a class="dropdown-item" href="{% url 'AIpredictionapp:predictionlist' %}">수요예측 리스트</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:logout' %}?next={{ request.path }}">Logout</a>
      </li>
    </ul>
  </div>
  {% endif %}
    
  {% else %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          제품
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'articleapp:basketproduct' %}">스마트바구니</a>
          <a class="dropdown-item" href="{% url 'articleapp:AIproduct' %}">AI수요예측 서비스</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'AIpredictionapp:AIservice' %}">서비스</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articleapp:pricing' %}">가격</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articleapp:inquiry' %}">제품문의</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questionapp:index' %}">Q&A</a>
      </li>
    </ul>
  </div>
  {% if not user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:login' %}?next={{ request.path }}">Login</a>
      </li>
    </ul>
  </div>
  {% else %}
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          계정관리
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'accountapp:detail' pk=user.pk %}">내 프로필</a>
          <a class="dropdown-item" href="{% url 'AIpredictionapp:predictionlist' %}">수요예측 리스트</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accountapp:logout' %}?next={{ request.path }}">Logout</a>
      </li>
    </ul>
  </div>
  {% endif %}
  {% endif %}  
</nav>