accountapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accountapp.views import AccountDeleteView, AccountCreateView, AccountDetailView, AccountUpdateView

app_name = "accountapp"


urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path 
from django.views.generic import TemplateView
import articleapp.views 

app_name = 'articleapp'

urlpatterns = [
    path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('basketproduct/', articleapp.views.basketproduct, name='basketproduct'),
    path('AIproduct/', articleapp.views.AIproduct, name='AIproduct'),
    path('pricing/', articleapp.views.pricing, name='pricing'),
    path('inquiry/', articleapp.views.inquiry, name='inquiry'),
    path('otherinfo/', articleapp.views.otherinfo, name='otherinfo'),
    path('terms/', articleapp.views.terms, name='terms'),
    path('companyinfo/', articleapp.views.companyinfo, name='companyinfo'),
    path('teaminfo/', articleapp.views.teaminfo, name='teaminfo'),
    path('checkout/', articleapp.views.check, name='checkout'),
] 

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 
from articleapp.views import *
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='articleapp/list.html'), name ='lists'),
    path('accounts/', include('accountapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('questions/', include('questionapp.urls')),
    path('AIpredictions/', include('AIpredictionapp.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.db import models
from django.views.generic import ListView

# Create your models here.

class Inquiry(models.Model):
    name = models.CharField('이름', max_length = 20, blank = False)
    location = models.CharField('위치', max_length = 100, blank = False)
    phone = models.CharField('헨드폰 번호',max_length = 20, blank = False)
    email_address = models.EmailField('이메일 주소', blank=False)
    agreement = models.BooleanField('동의서', default=False, blank = False)
    
    def __str__(self):
        return self.name 

articleapp/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import Inquiry

class InquiryForm(ModelForm):
    agreement = forms.BooleanField()
    class Meta:
        model = Inquiry
        fields = "__all__"
        labels = {
			'name': '',
			'phone': '',
			'email_address': '',
			'location': '',		
		}
        widgets = {
			'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'이름'}),
			'location': forms.TextInput(attrs={'class':'form-control', 'placeholder':'매장 위치'}),
			'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'핸드폰 번호 (- 없이 작성해주시기 바랍니다)'}),
			'email_address': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'이메일 주소'}),
		}

articleapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import InquiryForm

# Create your views here.
def basketproduct(request):
    return render(request, 'articleapp/basketproduct.html')

def AIproduct(request):
    return render(request, 'articleapp/AIproduct.html')

def check(request):
    return render(request, 'articleapp/check.html')

def pricing(request):
    return render(request, 'articleapp/pricing.html')

def inquiry(request):
    submitted = False
    if request.method == "POST":
        form = InquiryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/articles/inquiry?submitted=True')
    else:
        form = InquiryForm
        if 'submitted' in request.GET:
            submitted = True
    form = InquiryForm
    return render(request, 'articleapp/inquiry.html', {'form':form, 'submitted':submitted})



def companyinfo(request):
    return render(request, 'articleapp/companyinfo.html')

def otherinfo(request):
    return render(request, 'articleapp/otherinfo.html')

def terms(request):
    return render(request, 'articleapp/terms.html')

def teaminfo(request):
    return render(request, 'articleapp/teaminfo.html')

articleapp/templates/articleapp/basketproduct.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<html lang="en">

  <body>
<link href="{% static 'product.css' %}" rel="stylesheet">
      
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1>스마트바구니를 이용한 무인 간편 결제 시스템</h1>
    <p class="lead font-weight-normal">줄설필요 없는, 지갑이 필요없는, 시간제약없는 PX로 만들어드립니다. 높은 공간효율성으로 빠르고 쉬운 무인 결제 시스템을 경험해 보세요!</p>
    <a class="btn btn-outline-secondary" href="#">상담문의 바로가기</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-primary mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>

{% endblock %}

articleapp/templates/articleapp/companyinfo.html
{% extends 'base.html' %}

{% block content %}

<div>
    회사소개 
</div>

{% endblock %}

articleapp/templates/articleapp/inquiry.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    {% if submitted %}
    <h2>
        문의 신청을 완료됐습니다!
    </h2>
    <p>&nbsp;</p>
    <a href="{% url 'articleapp:list' %}">
        <button style='margin-top:1.1%' type="button" class="btn btn-outline-secondary btn-lg">&nbsp; &nbsp;홈으로 돌아가기&nbsp; &nbsp;</button>
    </a>
    <p>&nbsp;</p>
    {% else %}
    <div>
        <h4>
            <strong>지금 바로 무료 상담을 받아보세요!</strong>
        </h4>
        <p style="text-align: left;">
            부담없이 상담을 신청해주세요! 
            상담 신청시 상담원이 친철하게 매장별 맞춤 상담을 해드립니다.   
        </p>
    </div>
        <form action="" method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="문의하기" class="btn btn-secondary">
        </form>
    {% endif %}
</div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<html lang="en">
  <body>
<style>
    body {
      padding-bottom: 3rem;
      color: #5a5a5a;
    }


    /* CUSTOMIZE THE CAROUSEL
    -------------------------------------------------- */

    /* Carousel base class */
    .carousel {
      margin-bottom: 4rem;
    }
    /* Since positioning the image, we need to help out the caption */
    .carousel-caption {
      bottom: 3rem;
      z-index: 10;
    }

    /* Declare heights because of positioning of img element */
    .carousel-item {
      height: 32rem;
    }
    .carousel-item > img {
      position: absolute;
      top: 0;
      left: 0;
      min-width: 100%;
      height: 32rem;
    }


    /* MARKETING CONTENT
    -------------------------------------------------- */

    /* Center align the text within the three columns below the carousel */
    .marketing .col-lg-4 {
      margin-bottom: 1.5rem;
      text-align: center;
    }
    .marketing h2 {
      font-weight: 400;
    }
    .marketing .col-lg-4 p {
      margin-right: .75rem;
      margin-left: .75rem;
    }


    /* Featurettes
    ------------------------- */

    .featurette-divider {
      margin: 5rem 0; /* Space out the Bootstrap <hr> more */
    }

    /* Thin out the marketing headings */
    .featurette-heading {
      font-weight: 300;
      line-height: 1;
      letter-spacing: -.05rem;
    }


    /* RESPONSIVE CSS
    -------------------------------------------------- */

    @media (min-width: 40em) {
      /* Bump up size of carousel content */
      .carousel-caption p {
        margin-bottom: 1.25rem;
        font-size: 1.25rem;
        line-height: 1.4;
      }

      .featurette-heading {
        font-size: 50px;
      }
    }

    @media (min-width: 62em) {
      .featurette-heading {
        margin-top: 7rem;
      }
    }
</style>

<main role="main">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label=" :  " preserveAspectRatio="xMidYMid slice" focusable="false"><title> </title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"> </text></svg>

        <div class="container">
          <div class="carousel-caption text-left">
            <h1>무인간편결제 시스템</h1>
            <p>스마트바구니를 이용한 결제 무인화 서비스</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'articleapp:inquiry' %}">상담 문의하기</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label=" :  " preserveAspectRatio="xMidYMid slice" focusable="false"><title> </title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"> </text></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>매장 자동화 서비스</h1>
            <p>인공지능을 이용한 수요예측, 재고관리및 업무 자동화 서비스</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'articleapp:inquiry' %}">상담 문의하기</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label=" :  " preserveAspectRatio="xMidYMid slice" focusable="false"><title> </title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"> </text></svg>

        <div class="container">
          <div class="carousel-caption text-right">
            <h1>고객 관리 앱</h1>
            <p>전자영수증, 물품 투표, 포인트충전을 앱 하나로</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'articleapp:inquiry' %}">상담 문의하기</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-target="#myCarousel" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-target="#myCarousel" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">무인 매장, <span class="text-muted"> 스마트 바구니로 실현해보세요.</span></h2>
        <p class="lead">낮은 운영비, 높은 공간효율성, 고객 맞춤형 무인 결제 시스템을 소개합니다.</p>
        <a href="{% url 'articleapp:basketproduct' %}">
            <button style='margin-top:1.1%' type="button" class="btn btn-primary btn-lg">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;스마트 바구니 더보기&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</button>
        </a>
      </div>
      <div class="col-md-5">
        <img alt="" src="/static/Lineless_3D_modeling/drive.google.com_drive_folders_1q0Gxug7FqCqAa6xswA1Thgy3u4fvfSBc-removebg-preview.png" class="img-fluid w-100"/>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">매장 자동화 서비스<span class="text-muted"> Lineless의 인공지능으로 실현해보세요.</span></h2>
        <p class="lead">인공지능이 각 매장의 판매 데이터들을 학습하여 물품발주를 자동으로 정확히 예측하여 해줍니다. 수기로 진행되는 많은 업무들을 디지털화 하면서 효율성은 높이고 인건비는 줄여보세요.</p>
        <a href="{% url 'articleapp:AIproduct' %}">
            <button style='margin-top:1.1%' type="button" class="btn btn-primary btn-lg">&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;AI 수요예측 더보기&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</button>
        </a>
      </div>
      <div class="col-md-5 order-md-1">
        <img alt="" src="/static/Lineless_AI_models/graph1.png" class="img-fluid w-100"/>
        <img alt="" src="/static/Lineless_AI_models/graph2.png" class="img-fluid w-100"/>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">고객 관리 앱<span class="text-muted"> Lineless</span></h2>
        <p class="lead">고객들은 앱으로 전자영수증, 물품 투표, 포인트 관리를 앱 하나로 관리!</p>
      </div>
        <div class="row card-body;">
          <div class="col-sm my-3" style="align-items:center; display: flex; justify-content:center;">
            <div class="swiper" style="border-radius:2rem">
              <div class="swiper-wrapper" style="width: 380px;">
                <img class="swiper-slide" src="/static/Lineless_APP/8A11DE1B-D847-417C-903C-7F70C67301AA.png">
                <img class="swiper-slide" src="/static/Lineless_APP/D7ACDCE4-7C40-4897-A769-48A43D72D8A4.png">
                <img class="swiper-slide" src="/static/Lineless_APP/1ED4CAED-CE8C-49DA-A346-44EFA9609DCF.png">
              </div>
              <div class="swiper-pagination"></div>
              <div class="swiper-button-prev"></div>
              <div class="swiper-button-next"></div>
            </div>
          </div>
        </div>
    </div>

  </div><!-- /.container -->

</main>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>



{% endblock %}

articleapp/templates/articleapp/otherinfo.html
{% extends 'base.html' %}

{% block content %}

<div>
    공지사항
</div>

{% endblock %}

articleapp/templates/articleapp/pricing.html
{% extends 'base.html' %}

{% block content %}
<html>
  <body>
    
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check" viewBox="0 0 16 16">
    <title>Check</title>
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
</svg>

<div class="container py-3">
  <header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Pricing</h1>
      <p class="fs-5 text-muted">Lineless의 스마트바구니로 스마트 무인PX를 운영해보세요! 모든 서비스들을 첫한달간 무료로 체험해보실 수 있습니다.</p>
    </div>
  </header>

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Basic</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">₩150,000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>스마트바구니 10개 제공</li>
              <li>무료 상담 제공</li>
            </ul>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}"><button type="button" onclick="location.href='accountapp:login';" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button></a>
            {% else %}
            <a href="{% url 'articleapp:checkout' %}"><button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button></a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">₩300,000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>스마트바구니 15개 제공</li>
              <li>10개 제품에 대한 AI수요예측 서비스 제공</li>
              <li>무료 상담 제공</li>
              <li>온라인 PX컨설팅 서비스 제공</li>
              <li>자동 물품 발주 서비스 제공</li>
            </ul>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}"><button type="button" class="w-100 btn btn-lg btn-primary">Get started</button></a>
            {% else %}
            <a href="{% url 'articleapp:checkout' %}"><button type="button" class="w-100 btn btn-lg btn-primary">Get started</button></a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal">Enterprise</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">₩400,000<small class="text-muted fw-light">/mo</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>스마트바구니 20개 제공</li>
              <li>20개 제품에 대한 AI수요예측 서비스 제공</li>
              <li>무료 상담 제공</li>
              <li>온라인 PX컨설팅 서비스 제공</li>
              <li>자동 물품 발주 서비스 제공</li>
              <li>AI 도난방지 서비스 제공</li>
            </ul>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}"><button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button></a>
            {% else %}
            <a href="{% url 'articleapp:checkout' %}"><button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Compare plans</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Basic</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">스마트바구니 제공</th>
            <td>10개</td>
            <td>15개</td>
            <td>20개</td>
          </tr>
          <tr>
            <th scope="row" class="text-start">AI 수요예측 서비스 제공 (차등 제공)</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">무료 상담 제공</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">온라인 PX 컨설팅 제공</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">자동 물품 발주 서비스 제공</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">보안 서비스 제공</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div>
  </main>
</div>


    
  </body>
</html>
{% endblock %}